name = "kn-visuals-backend"
main = "src/index.js"
compatibility_date = "2026-10-03"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "kn_visuals"
database_id = "7b9e9eb2-754a-45a1-b1cc-b6daea725c40"
